services:
  postgres:
    image: postgres:16
    container_name: taskpilot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taskpilot
      POSTGRES_USER: taskpilot
      POSTGRES_PASSWORD: $ecreT
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "6432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
